**Introduction to text pre-processing**

Suppose you open Amazon.

You search
iPhone 15
How does Amazon know that you're searching for a mobile?

How does it understand your sentence?

Can a computer actually read English?"
(wait)

Students:
No...

Some:
Maybe...

Then smile.
Say
Actually...
Computers don't understand English.

Write on board

I Love Cricket
Ask
"What is this?"

Students
Sentence

Now ask
"What is this for computer?"
Students

Sentence

Say
"No."

Erase.

Write
73 32 55 18

Tell
"This is what computer actually sees."

"If computer cannot understand English...

How is ChatGPT talking to us?"

Now they'll become curious.

Then explain
Before machine understands language...
We have to clean the text.

Today's topic is
TEXT PREPROCESSING

Example:

Imagine...
You hired a new employee.

First day.
You tell him
Go to warehouse.
Bring Apple.

He returns with
🍎 Apple Fruit

But you wanted

💻 Apple Laptop

Question
Whose mistake?

Students
Employee
Exactly.

Because we didn't give context.

Computers have same problem.

When we write
Apple

Computer doesn't know

Fruit?
Company?
Logo?
Movie?
Music?

Everything is text.
x
That's why preprocessing is required.

Step 1: Start with a Question (2 mins)

Walk into the class and ask:

Trainer:
"Guys, suppose your friend sends you this message."

Hiiii!!!! 😍😍😍
I LOOOOOVE this phone!!!!!
Visit www.amazon.in
Call me at 9876543210

Ask them:
"Can we directly give this text to an NLP model?"

Most students will say Yes or Maybe.
Smile and say:
"No... because computers are not smart like humans."

Step 2: Explain What Raw Text Means
Say:

"The text that comes directly from users, websites, emails, WhatsApp, Twitter, Instagram, Amazon reviews... is called Raw Text."

Write on board
Raw Text
↓

Dirty
Messy
Unstructured
Contains Noise

Then ask:
"What problems can you see here?"

Show
Hiiii!!!! 😍😍😍
I LOOOOOVE this phone!!!!!
Visit www.amazon.in
Call me at 9876543210

"Exactly.
Before giving this to Machine Learning...
We have to CLEAN it."

Cleaning Process

Raw Text

↓

Lowercase

↓

Remove URLs

↓

Remove Numbers

↓

Remove Punctuation

↓

Remove Emoji

↓

Remove Extra Spaces

↓

Clean Text

In [ ]:
text = "Hiiii!!!! I LOOOOOVE Python 😍😍 Visit www.python.org"

Ask
"What should we remove?"
Students answer.
Then do step by step.

In [ ]:
# step 01: converting from capital to small
text = text.lower()
print(text)

hiiii!!!! i looooove python 😍😍 visit www.python.org

Ask
"What changed?"
Students
Capital became small.

In [ ]:
# step 02: removing URL

In [ ]:
import re
# Python doesn't know how to search patterns by default. So we import the re library.
# re = Regular Expression

text = re.sub(r'http\S+|www\S+', '', text)
# sub means subsitute - replace something with something
# syntax : # re.sub(pattern, replacement, text)
# pattern : what we are searching for ? website, phone number, email
# '' with what you are replace '' means nothing
# https : looks for word starting with https
# \S+ means 'keep taking every character until you reach a space

print(text)

hiiii!!!! i looooove python 😍😍 visit

In [ ]:
import re

In [ ]:
test = "Hi how are you this is meeting link www.amazon.in"

In [ ]:
test = re.sub(r'https\S+|www\S+', '', test)

In [ ]:
test

'Hi how are you this is meeting link '

Ask
"Why remove website?"
Expected answer
Website doesn't help understand sentiment.

Sentiment means the emotion, feeling, or opinion expressed in a piece of text.

In [ ]:
# step 03: Remove punctuation

In [ ]:
import string

text = text.translate(str.maketrans('', '', string.punctuation))
print(text)
# translate: it follows the rules which we created
# maketrnas : make - create trans - translate
# string.punctuation : This simply means: 'Give me all the punctuation symbols.' !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

hiiii i looooove python 😍😍 visit

In [ ]:
# Ask:  what disappear here ?

Ask the students:
Trainer: "What are the actual words here?"
Students will answer:
Hello
How
are
you
Python
NLP
Then ask:
"What are these?"
!!!
???
@
#
.
Students:
"Special symbols."
Then say:
"Exactly! These are called punctuation marks. In many NLP tasks, they don't add useful meaning, so we remove them."

In [ ]:
# step 04: Remove Numbers

In [ ]:
text1 = "shaaaz 1@"

In [ ]:
text1 = re.sub(r'\d+', '', text1)
text1 = text1.translate(str.maketrans('', '', string.punctuation))

In [ ]:
# re.sub() → Replace or remove a pattern.
# r'' → Raw string (Python reads the pattern as it is).
# \d → Any digit (0–9).
# + → One or more digits.
# '' → Replace with nothing (remove it).
# text → The text where the replacement happens.

In [ ]:
text1

'shaaaz '

In [ ]:
# remove extra space

In [ ]:
text1 = " ".join(text1.split())

print(text1)

shaaaz

In [ ]:
a = "shaaz.  "
b = "   mukadam"

In [ ]:
u = " ".join(b.split())

In [ ]:
u

'mukadam'

In [ ]:
# split() → Splits the sentence into words by removing extra spaces.
# " ".join() → Joins the words back together with one single space between them.

**Tokenization**

Good Morning Everyone

Ask the class:
Trainer: "How many words are written here?"

Students:

Good
Morning
Everyone

Then ask:
"Did anyone count the letters first?"

Students:
"No."

Then ask:
"What did your brain do first?"

Students:
"It separated the words."
Smile and say:

"Exactly! Our brain naturally separates a sentence into words. But a computer cannot do this by itself."

I

love

learning

Python

Ask the class:
"What did he do?"
Students:
"Split the sentence."

Then say:
"Exactly! In NLP, this process is called Tokenization."

In [ ]:
# coding

Write

HappyBirthdayRahul

Ask :
Can you read it?:
Yes.

Now ask
Could a computer read it?
Not easily.

Need

Happy

Birthday

Rahul

Now introduce
Token = Small meaningful unit.

Write

Artificial Intelligence is changing the world.

Ask:

Split this sentence manually.
Expected

Artificial

Intelligence

is

changing

the

world

Now ask

"How many tokens?"
Students answer.

In [ ]:
# can 5 people eat a single pizza without cutting it ? No
# if we cut it into 5 pices so they can it easily so same thing we have to apply here

In [ ]:
from nltk.tokenize import word_tokenize
import nltk
# import the NLTK (Natural Language Toolkit) library.
# from nltk.tokenize → Go to the tokenize module inside the NLTK library.
# import word_tokenize → Import the function that splits a sentence into words (tokens).

nltk.download('punkt')
nltk.download('punkt_tab')
# Download tokenizer data (only first time)



text = "I love learning NLP."


tokens = word_tokenize(text)

print(tokens)

['I', 'love', 'learning', 'NLP', '.']

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [ ]:
# But NLP models first convert text into tokens because they work word by word.

In [ ]:
text = "Python is awesome!"

Sentence Tokenization

I love Python. I also love Machine Learning. NLP is interesting.


"How many sentences are there?"

Students
3

Now explain:

Sometimes we don't want words. We want to split a paragraph into separate sentences.

In [ ]:
from nltk.tokenize import sent_tokenize

text = "I love Python. I also love Machine Learning. NLP is interesting."

sentences = sent_tokenize(text)

print(sentences)

['I love Python.', 'I also love Machine Learning.', 'NLP is interesting.']

Character Tokenization

In [ ]:
text = "Hello"

characters = list(text)

print(characters)

['H', 'e', 'l', 'l', 'o']

The type of tokenization depends on the problem we are solving.

Real World **Example 1: **Google Search


Best laptop under 50000


"Does Google search character by character?"

Students : "No"

Does it search sentence by sentence?
"No"

It mainly focuses on
Words
Because

Laptop

Best

50000

These carry the meaning.

Therefore
Google mostly uses
Word Tokenization

Real World Example 2
WhatsApp

Suppose your friend sends

Hello.

How are you?

Are you coming today?


"How many messages are there?"

Students
3 sentences

Now suppose you are building
AI that counts
How many sentences people send.

Will Word Tokenization help?

No.
Need
Sentence Tokenization


Real World Example 3

Password Checker

Write
Password@123


"Suppose I want to check..."

Does password contain
Capital Letter?
Number?
Special Character?
How should I check?

Whole sentence?
No.

Words?
No.

Need
P

a

s

s

w

o

r

d

@

1

2

3

Need
Character Tokenization.

Real World Example (Netflix)

Tell them
Suppose Netflix wants to know

Whether a review is

Positive

Negative

Example

This movie is fantastic.


Should Netflix analyze
Characters?

Students
"No"

Whole paragraph?
"No"

Important words

movie

fantastic

Hence
Word Tokenization.

Stopwords

Learning Outcome
By the end of the session students should know:

What stopwords are

Why we remove them

When we should NOT remove them

How to remove stopwords using NLTK

Real-world applications

The boy is sitting on the chair.

A STOPWORD :

"If I remove only the important words from this sentence, which words will you keep?"

Let students answer.
Expected answers:

boy

sitting

chair

Now write:

boy sitting chair


"Can you still understand what happened?"

Students will say:
"Yes."

Now ask:
"Then why do we need words like the, is, and on?"

Let them think.
After a minute, say:

"These words help us speak grammatically, but in many NLP tasks they don't add much meaning."

Now reveal the topic:
STOPWORDS

Real-Life Example
Google Search


"When you search on Google, do you type this?"

What is the best mobile phone under 30000?

Or do you type:

best mobile phone under 30000

Students usually answer:

"Best mobile phone under 30000."

Now ask:
"Why didn't you type what, is, and the?"

Because they don't change the search intent much.

Write:
What is the best

mobile phone
↓
best mobile phone

Now explain:

Google often focuses on the important words because they carry the main meaning.

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import nltk

In [ ]:
# word_tokenize() splits text into words
# stopwords gives us a ready-made list of common words

In [ ]:
# create text

In [ ]:
text = "The boy is playing in the garden."

In [ ]:
# tokenize

In [ ]:
tokens = word_tokenize(text)

print(tokens)

LookupError:
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

which word looks important ?

boy

playing

garden

In [ ]:
# load stop words

In [ ]:
stop_words = set(stopwords.words('english'))

print(stop_words)
# this will gives 100 of common english stopwords

{'the', 'him', 'shan', 'hasn', 'myself', 'and', 'now', 'he', 't', "they'll", "i'm", 'with', "couldn't", 'd', "aren't", 'too', 'was', "won't", "didn't", 'there', 'from', 'nor', 'she', 'on', "we'll", 'does', 'am', 'if', 'only', 'mustn', 'they', 'what', 'each', "i've", 'my', 'while', 'above', "should've", 'for', 'just', 'between', "weren't", 'where', 'about', 've', 'at', 'did', "hadn't", 'll', 'itself', "she'll", 'her', 'here', 'few', 'over', 'after', 'until', 'hadn', 'an', 'why', "isn't", 'had', "we've", 'than', 'so', 'down', "it's", 'of', 'be', 'such', 'that', 'these', 'ourselves', "mustn't", 'y', 'very', "doesn't", "they're", 'are', 'couldn', "shan't", 'any', "they'd", 'ma', "hasn't", 'have', 'shouldn', 'this', 'yours', "shouldn't", 'is', 'isn', 'will', 'how', 'needn', 'out', 'some', 'against', "we'd", 'again', 'when', "you'll", "i'd", 'hers', 'themselves', "mightn't", 'should', 'below', 'or', "you'd", 'both', 'o', 'to', "i'll", "wasn't", 'during', 'weren', 'own', 'because', 'wouldn', 'same', 'ours', "haven't", 'off', 'most', 'by', 'as', 'ain', "don't", 'being', 'it', "that'll", 'further', 'can', 'doesn', 'herself', 'i', 'a', 'up', 'whom', "he'd", 'no', 'not', 'having', "you're", 'who', 'do', "he'll", 'you', 'once', 'our', 'all', 'through', "needn't", "he's", 'into', 'm', 'those', 'his', 'aren', "it'd", 'doing', 'has', 'me', 'mightn', "they've", 'but', 'haven', "she's", 'under', 'your', 'yourselves', 'wasn', 'which', 'didn', 're', 'their', 'were', 'won', 'other', "you've", 'himself', "wouldn't", 'don', "she'd", 'theirs', 'then', "we're", 'them', 's', "it'll", 'in', 'been', 'more', 'yourself', 'before', 'we', 'its'}

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
# removing stop words

In [ ]:
filtered_words = []
# Creates an empty list to store useful words.

for word in tokens:
# check every token one by one

    if word.lower() not in stop_words:
      #word.lower() : convert the word in lower case
      # why we do this lower the and The will be treated as same
      # Checks whether the word is not a stopword.
        filtered_words.append(word)
# Adds only meaningful words to the new list.
print(filtered_words)

['boy', 'playing', 'garden', '.']

Should We Always
Remove Stopwords?

I like this movie.

I do not like this movie.

"Which word changes the meaning completely?"

Students:
not

Now remove stopwords.

like movie
like movie

Ask:
"Are these two sentences still different?"

Students:
"No."

Now explain:
This is why we should not always remove stopwords.


Real-World Example
Sentiment Analysis

I love this movie.
Positive

I do not love this movie.
Negative

Removing not would completely change the meaning.

So for tasks like sentiment analysis, many developers keep words like not, no, and never.

This is one of the most important practical points students should remember.

Simple Definition

Sentiment Analysis is the process of finding the emotion or opinion expressed in a piece of text.

In simple words:

The computer tries to understand whether the text is Positive, Negative, or Neutral.

Real-Life Example 1 (Amazon Reviews)

Suppose a customer writes:

This phone is amazing.
Computer predicts:
😊 Positive

Another customer writes:
Worst phone I have ever used.
Computer predicts:
😞 Negative

Another customer writes:
The phone weighs 180 grams.
Computer predicts:
😐 Neutral

Because this sentence only gives information and does not express an opinion.

"We don't remove stopwords in sentiment analysis."

Instead, prove it.

Sentence 1

I like this movie.

Ask
"Raise your hand if this is a Positive Review."

Everyone raises their hand.
Write
😊 Positive

Now write another sentence.
Sentence 2

I do not like this movie.

Ask
"Positive or Negative?"
Students
Negative

Now ask
"Which ONE word changed the entire meaning?"

Students will immediately answer

not

Now circle not on the board.

Now tell them
"Suppose I blindly remove stopwords."

Write
I do not like this movie.
↓
Remove stopwords
↓
like movie

Now compare.

Sentence 1

like movie

Sentence 2
like movie

"Can you now tell which review was positive and which was negative?"

Students
No

Exactly!
Big Conclusion

Tell them
"The computer is not wrong. We removed the word that carried the emotion."

Write on the board
NOT

is a Stopword

BUT

NOT

changes meaning.

Another Real Example
(Bank)

SMS
Transaction Successful.
Another SMS
Transaction not Successful.

Remove stopwords
Both become

Transaction Successful
Ask
Imagine bank software does this.
Problem?
Students laugh.
Exactly.

In [ ]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

text = "I do not like this movie."

tokens = word_tokenize(text)

print(tokens)

['I', 'do', 'not', 'like', 'this', 'movie', '.']


Ask students
Which word is important?
Students
NOT
Now

In [ ]:
stop_words = set(stopwords.words("english"))

filtered = []

for word in tokens:

    if word.lower() not in stop_words:

        filtered.append(word)

print(filtered)

['like', 'movie', '.']

Ask
Where is NOT?
Students
Gone.
Now ask
Meaning changed?
YES

Now Show Industry Solution
Tell students
"Does this mean we never remove stopwords?"
Students
No.
Tell them
"We remove MOST stopwords but KEEP important ones."

In [ ]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

In [ ]:
# remove important words from the stopword

In [ ]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

important_words = ["not", "no", "never"]

for word in important_words:
    stop_words.discard(word)   # No error if word is absent

print("not" in stop_words)

False

In [ ]:
# Explain
# False means NOT is no longer treated as a stopword.

In [ ]:
from nltk.tokenize import sent_tokenize
import nltk

# Download the tokenizer model (only the first time)
nltk.download("punkt")
nltk.download("punkt_tab")

text = """
Today I woke up early.
I went for a walk.
Then I attended my NLP class.
"""

sentences = sent_tokenize(text)

print(sentences)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

['\nToday I woke up early.', 'I went for a walk.', 'Then I attended my NLP class.']

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [ ]:
from nltk.tokenize import sent_tokenize

paragraph = """
The customer ordered a laptop online. The delivery arrived the next day. The customer left a five-star review.
"""

sentences = sent_tokenize(paragraph)

for i, sentence in enumerate(sentences, start=1):
    print(f"Sentence {i}: {sentence}")

Sentence 1:
The customer ordered a laptop online.
Sentence 2: The delivery arrived the next day.
Sentence 3: The customer left a five-star review.

Write this on the board.


Run
Running
Runs
Runner
Ran

"Are these five completely different words?"

"No."


"What is common among all of them?"


"They all talk about running."
Exactly


"If I search Google for 'running shoes', should Google also show results for 'run shoes'?"
Students
"Yes."


"Why?"
"Because both mean almost the same thing."


"Exactly! But computers don't automatically know that."

Today's topic:

STEMMING


Real-Life Example 1 (Google Search)

Write

Running Shoes

"If a shop writes 'Run Shoes' and you search 'Running Shoes', should that shop disappear from the results?"

"No."


Instead of remembering

Run

Running

Runs

Runner

Google stores one common form

Explain
"This process of reducing similar words to a common base is called stemming."


Activity 1

Write

Play

Playing

Played

Player

Plays

Ask one student

"What is the common idea?"
Students

Play

Now another example

Read

Reading

Reads

Reader

Common idea
Read


"Do we really need to store all five words separately?"

Students
"No."

Tell students:
"Imagine your college has five students."

Rahul
Rahul Kumar
R. Kumar
Rahul K.
Mr. Rahul
Ask
"Are these five different people?"
Students
"No."
Exactly.

Now say
"A computer might think they are five different names."
So we convert them to one standard representation.

Similarly

Running

Runs

Runner

becomes

Run

Critical Thinking Question

Ask
"Suppose Amazon has one review saying 'running is fun' and another saying 'run is fun'. Should AI treat them as two completely different ideas?"
Students
"No."

Ask
"Then what should AI do?"

Students
"Convert both to the same root."
Exactly.

In [ ]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

words = [
    "running",
    "played",
    "playing",
    "studies",
    "happiness"
]

for word in words:
    print(word, " --> ", stemmer.stem(word))

running  -->  run
played  -->  play
playing  -->  play
studies  -->  studi
happiness  -->  happi

Start with an Interaction

Walk into class and ask:

"Suppose two teachers are checking your exam paper."

Teacher A

Very strict
Follows old rules

Teacher B
More flexible
Uses updated rules


"Will both teachers always give the same marks?"
Students
"No."

Now connect it.
Porter and Snowball are like two teachers.

Both try to reduce words to their root form, but they follow different sets of rules.

When Should We Use Porter?

Use Porter when:
You're working only with English.

You want a simple, classic stemming algorithm.
You're learning how stemming works.

When Should We Use Snowball?
Use Snowball when:
You need support for multiple languages.

In [ ]:
from nltk.stem import SnowballStemmer

print(SnowballStemmer.languages)

('arabic', 'danish', 'dutch', 'english', 'finnish', 'french', 'german', 'hungarian', 'italian', 'norwegian', 'porter', 'portuguese', 'romanian', 'russian', 'spanish', 'swedish')

In [ ]:
from nltk.stem import PorterStemmer
from nltk.stem import SnowballStemmer

porter = PorterStemmer()

snowball = SnowballStemmer("english")

words = [
    "running",
    "studies",
    "playing",
    "connected",
    "connection",
    "happiness"
]

for word in words:

    print("Original :", word)

    print("Porter :", porter.stem(word))

    print("Snowball :", snowball.stem(word))

    print("-"*30)

Original : running
Porter : run
Snowball : run
------------------------------
Original : studies
Porter : studi
Snowball : studi
------------------------------
Original : playing
Porter : play
Snowball : play
------------------------------
Original : connected
Porter : connect
Snowball : connect
------------------------------
Original : connection
Porter : connect
Snowball : connect
------------------------------
Original : happiness
Porter : happi
Snowball : happi
------------------------------

Lemmatization

Lemmatization is the process of converting a word into its original dictionary form (called the lemma).


Suppose you go to a library.
You search for:
Running
Will the dictionary have a page named Running?
No.
You'll find
Run

Running
      │
      ▼
Dictionary Search
      │
      ▼
Run

In [ ]:
import pandas as pd

In [ ]:
text = pd.read_csv('synthetic_text_cleaning_realworld.csv')

In [ ]:
text

,id,user_id,username,email,phone_number,tweet_text,post_text,comment_text,review_text,bio_text,...,product_description,advertisement_text,song_lyrics,movie_script,news_snippet,blog_text,story_text,job_description,company_profile,misc_text
0,1,Download now >>> free link http://spam.com,Data cleaning is very IMPORTANT.....,Check this out >>> https://openai.com,U r the best!! btw I'll c u 2morrow 😉,Data cleaning is very IMPORTANT.....,Email me at test_user123@gmail.com asap!!!,U r the best!! btw I'll c u 2morrow 😉,Café München is beautïful but costly $$$,Download now >>> free link http://spam.com,...,Heeeyyy broooo wassuppp??? 😂😂😂,Breaking news!!!! #AI #NLP @research,Café München is beautïful but costly $$$,Download now >>> free link http://spam.com,RT @someone: This is a RETWEET with #hashtag,Breaking news!!!! #AI #NLP @research,Download now >>> free link http://spam.com,Café München is beautïful but costly $$$,Breaking news!!!! #AI #NLP @research,Download now >>> free link http://spam.com
1,2,Stopwords should be removed from this text in ...,Check this out >>> https://openai.com,Email me at test_user123@gmail.com asap!!!,"Working on NLP??? It's fun, isn't it???",Café München is beautïful but costly $$$,Heeeyyy broooo wassuppp??? 😂😂😂,Heeeyyy broooo wassuppp??? 😂😂😂,123456789 Numbers should be removed!!!,Café München is beautïful but costly $$$,...,Café München is beautïful but costly $$$,123456789 Numbers should be removed!!!,This TEXT has MULTIPLE spaces and --- dash...,U r the best!! btw I'll c u 2morrow 😉,Email me at test_user123@gmail.com asap!!!,Check this out >>> https://openai.com,U r the best!! btw I'll c u 2morrow 😉,Check this out >>> https://openai.com,123456789 Numbers should be removed!!!,<p>Python is GREAT!!!</p> Visit http://example...
2,3,Heeeyyy broooo wassuppp??? 😂😂😂,Stopwords should be removed from this text in ...,Email me at test_user123@gmail.com asap!!!,Café München is beautïful but costly $$$,Breaking news!!!! #AI #NLP @research,Email me at test_user123@gmail.com asap!!!,Data cleaning is very IMPORTANT.....,Check this out >>> https://openai.com,Hello!!! This is a SAMPLE text 😊.,...,Breaking news!!!! #AI #NLP @research,"Working on NLP??? It's fun, isn't it???",U r the best!! btw I'll c u 2morrow 😉,This TEXT has MULTIPLE spaces and --- dash...,RT @someone: This is a RETWEET with #hashtag,Download now >>> free link http://spam.com,Stopwords should be removed from this text in ...,Hello!!! This is a SAMPLE text 😊.,123456789 Numbers should be removed!!!,123456789 Numbers should be removed!!!
3,4,Café München is beautïful but costly $$$,Data cleaning is very IMPORTANT.....,U r the best!! btw I'll c u 2morrow 😉,Stopwords should be removed from this text in ...,U r the best!! btw I'll c u 2morrow 😉,Data cleaning is very IMPORTANT.....,Data cleaning is very IMPORTANT.....,This TEXT has MULTIPLE spaces and --- dash...,Email me at test_user123@gmail.com asap!!!,...,Breaking news!!!! #AI #NLP @research,Stopwords should be removed from this text in ...,This TEXT has MULTIPLE spaces and --- dash...,<p>Python is GREAT!!!</p> Visit http://example...,Café München is beautïful but costly $$$,Café München is beautïful but costly $$$,Breaking news!!!! #AI #NLP @research,123456789 Numbers should be removed!!!,Email me at test_user123@gmail.com asap!!!,Download now >>> free link http://spam.com
4,5,This TEXT has MULTIPLE spaces and --- dash...,This TEXT has MULTIPLE spaces and --- dash...,Check this out >>> https://openai.com,"Working on NLP??? It's fun, isn't it???",123456789 Numbers should be removed!!!,Hello!!! This is a SAMPLE text 😊.,U r the best!! btw I'll c u 2morrow 😉,U r the best!! btw I'll c u 2morrow 😉,Heeeyyy broooo wassuppp??? 😂😂😂,...,Email me at test_user123@gmail.com asap!!!,This TEXT has MULTIPLE spaces and --- dash...,Check this out >>> https://openai.com,Hello!!! This is a SAMPLE text 😊.,Check this out >>> https://openai.com,Café München is beautïful but costly $$$,Check this out >>> https://openai.com,Heeeyyy broooo wassuppp??? 😂😂😂,U r the best!! btw I'll c u 2morrow 😉,Café München is beautïful but costly $$$
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Café München is beautïful but costly $$$,Email me at test_user123@gmail.com asap!!!,Data cleaning is very IMPORTANT.....,This TEXT has MULTIPLE spaces and --- dash...,Check this out >>> https://openai.com,Café München is beautïful but costly $$$,Café München is beautïful but costly $$$,Café München is beautïful but costly $$$,<p>Python is GREAT!!!</p> Visit http://example...,...,Breaking news!!!! #AI #NLP @research,Stopwords should be removed from this text in ...,Check this out >>> https://openai.com,Email me at test_user123@gmail.com asap!!!,123456789 Numbers should be removed!!!,Check this out >>> https://openai.com,RT @someone: This is a RETWEET with #hashtag,Check this out >>> https://openai.com,Email me at test_user123@gmail.com asap!!!,Download now >>> free link http://spam.com
1996,1997,Café München is beautïful but costly $$$,"Working on NLP??? It's fun, isn't it???",Email me at test_user123@gmail.com asap!!!,123456789 Numbers should be removed!!!,Stopwords should be removed from this text in ...,123456789 Numbers should be removed!!!,This TEXT has MULTIPLE spaces and --- dash...,123456789 Numbers should be removed!!!,Download now >>> free link http://spam.com,...,Check this out >>> https://openai.com,This TEXT has MULTIPLE spaces and --- dash...,"Working on NLP??? It's fun, isn't it???",Hello!!! This is a SAMPLE text 😊.,This TEXT has MULTIPLE spaces and --- dash...,Breaking news!!!! #AI #NLP @research,Data cleaning is very IMPORTANT.....,Breaking news!!!! #AI #NLP @research,Hello!!! This is a SAMPLE text 😊.,<p>Python is GREAT!!!</p> Visit http://example...
1997,1998,Breaking news!!!! #AI #NLP @research,Stopwords should be removed from this text in ...,<p>Python is GREAT!!!</p> Visit http://example...,Email me at test_user123@gmail.com asap!!!,"Working on NLP??? It's fun, isn't it???",Download now >>> free link http://spam.com,Check this out >>> https://openai.com,This TEXT has MULTIPLE spaces and --- dash...,Café München is beautïful but costly $$$,...,This TEXT has MULTIPLE spaces and --- dash...,U r the best!! btw I'll c u 2morrow 😉,Café München is beautïful but costly $$$,Heeeyyy broooo wassuppp??? 😂😂😂,Stopwords should be removed from this text in ...,Café München is beautïful but costly $$$,U r the best!! btw I'll c u 2morrow 😉,U r the best!! btw I'll c u 2morrow 😉,123456789 Numbers should be removed!!!,Download now >>> free link http://spam.com
1998,1999,"Working on NLP??? It's fun, isn't it???",123456789 Numbers should be removed!!!,"Working on NLP??? It's fun, isn't it???",U r the best!! btw I'll c u 2morrow 😉,"Working on NLP??? It's fun, isn't it???",Breaking news!!!! #AI #NLP @research,123456789 Numbers should be removed!!!,RT @someone: This is a RETWEET with #hashtag,This TEXT has MULTIPLE spaces and --- dash...,...,123456789 Numbers should be removed!!!,Café München is beautïful but costly $$$,U r the best!! btw I'll c u 2morrow 😉,RT @someone: This is a RETWEET with #hashtag,Heeeyyy broooo wassuppp??? 😂😂😂,Email me at test_user123@gmail.com asap!!!,Hello!!! This is a SAMPLE text 😊.,<p>Python is GREAT!!!</p> Visit http://example...,Data cleaning is very IMPORTANT.....,Café München is beautïful but costly $$$
1999,2000,Stopwords should be removed from this text in ...,Data cleaning is very IMPORTANT.....,Hello!!! This is a SAMPLE text 😊.,Stopwords should be removed from this text in ...,Hello!!! This is a SAMPLE text 😊.,Hello!!! This is a SAMPLE text 😊.,"Working on NLP??? It's fun, isn't it???",Heeeyyy broooo wassuppp??? 😂😂😂,Café München is beautïful but costly $$$,...,This TEXT has MULTIPLE spaces and --- dash...,Breaking news!!!! #AI #NLP @research,This TEXT has MULTIPLE spaces and --- dash...,Check this out >>> https://openai.com,Breaking news!!!! #AI #NLP @research,<p>Python is GREAT!!!</p> Visit http://example...,Email me at test_user123@gmail.com asap!!!,This TEXT has MULTIPLE spaces and --- dash...,This TEXT has MULTIPLE spaces and --- dash...,"Working on NLP??? It's fun, isn't it???"

In [ ]:
text.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2000 non-null   int64
 1   user_id              2000 non-null   object
 2   username             2000 non-null   object
 3   email                2000 non-null   object
 4   phone_number         2000 non-null   object
 5   tweet_text           2000 non-null   object
 6   post_text            2000 non-null   object
 7   comment_text         2000 non-null   object
 8   review_text          2000 non-null   object
 9   bio_text             2000 non-null   object
 10  headline             2000 non-null   object
 11  article_text         2000 non-null   object
 12  message_text         2000 non-null   object
 13  chat_text            2000 non-null   object
 14  status_text          2000 non-null   object
 15  caption_text         2000 non-null   object
 16  forum_post           2000 non-null   object
 17  question_text        2000 non-null   object
 18  answer_text          2000 non-null   object
 19  feedback_text        2000 non-null   object
 20  product_description  2000 non-null   object
 21  advertisement_text   2000 non-null   object
 22  song_lyrics          2000 non-null   object
 23  movie_script         2000 non-null   object
 24  news_snippet         2000 non-null   object
 25  blog_text            2000 non-null   object
 26  story_text           2000 non-null   object
 27  job_description      2000 non-null   object
 28  company_profile      2000 non-null   object
 29  misc_text            2000 non-null   object
dtypes: int64(1), object(29)
memory usage: 468.9+ KB

In [ ]:
text["tweet_text"]

0          Data cleaning   is      very    IMPORTANT.....
1                Café München is beautïful but costly $$$
2                    Breaking news!!!! #AI #NLP @research
3                   U r the best!! btw I'll c u 2morrow 😉
4                  123456789 Numbers should be removed!!!
                              ...
1995                Check this out >>> https://openai.com
1996    Stopwords should be removed from this text in ...
1997              Working on NLP??? It's fun, isn't it???
1998              Working on NLP??? It's fun, isn't it???
1999                    Hello!!! This is a SAMPLE text 😊.
Name: tweet_text, Length: 2000, dtype: object

**Text Data PreProcessing**

1. Converting into lower case

In [ ]:
text["tweet_text"] = text["tweet_text"].str.lower()

In [ ]:
text['tweet_text']

0          data cleaning   is      very    important.....
1                café münchen is beautïful but costly $$$
2                    breaking news!!!! #ai #nlp @research
3                   u r the best!! btw i'll c u 2morrow 😉
4                  123456789 numbers should be removed!!!
                              ...
1995                check this out >>> https://openai.com
1996    stopwords should be removed from this text in ...
1997              working on nlp??? it's fun, isn't it???
1998              working on nlp??? it's fun, isn't it???
1999                    hello!!! this is a sample text 😊.
Name: tweet_text, Length: 2000, dtype: object

2. Removing all HTML tags

In [ ]:
# beautifulsoap is used to read html and xml tag and used to remove it from text

In [ ]:
from bs4 import BeautifulSoup

text["tweet_text"] = text["tweet_text"].apply(
    lambda x: BeautifulSoup(str(x), "html.parser").get_text()
)

print(text["tweet_text"].head())

0    data cleaning   is      very    important.....
1          café münchen is beautïful but costly $$$
2              breaking news!!!! #ai #nlp @research
3             u r the best!! btw i'll c u 2morrow 😉
4            123456789 numbers should be removed!!!
Name: tweet_text, dtype: object

3. Remove URL

In [ ]:
import re

# Function to remove URLs
def remove_url(text):
    return re.sub(r'https?://\S+|www\.\S+', '', str(text))
# matches URLS that starts with http or https
# /S means non space character

# Apply the function to the column
text["tweet_text"] = text["tweet_text"].apply(remove_url)

# Display first 5 rows
print(text["tweet_text"].head())

0    data cleaning   is      very    important
1           caf mnchen is beautful but costly
2                breaking news ai nlp research
3            u r the best btw ill c u 2morrow
4          123456789 numbers should be removed
Name: tweet_text, dtype: object

4. Removing only HashTag

In [ ]:
import re

# Function to remove only the '#' symbol
def remove_hashtag(text):
    return re.sub(r"#", "", str(text))

# Apply the function to the column
text["tweet_text"] = text["tweet_text"].apply(remove_hashtag)

# Display first 5 rows
print(text["tweet_text"].head())

0    data cleaning   is      very    important
1           caf mnchen is beautful but costly
2                breaking news ai nlp research
3            u r the best btw ill c u 2morrow
4          123456789 numbers should be removed
Name: tweet_text, dtype: object

5. Removing Puncuation marks

In [ ]:
import string

# Function to remove punctuation
def remove_punctuation(text):
    return str(text).translate(str.maketrans('', '', string.punctuation))

# Apply the function to the column
text["tweet_text"] = text["tweet_text"].apply(remove_punctuation)

# Display first 5 rows
print(text["tweet_text"].head())

0    data cleaning   is      very    important
1           caf mnchen is beautful but costly
2                breaking news ai nlp research
3            u r the best btw ill c u 2morrow
4          123456789 numbers should be removed
Name: tweet_text, dtype: object

6. Remove Special word

In [ ]:
import re

# Function to remove special characters
# Keeps only alphabets (A-Z, a-z), numbers (0-9), and spaces
def remove_special_characters(text):
    return re.sub(r'[^a-zA-Z0-9\s]', '', str(text))
# [] sqauer bracket define character set
# ^ in square bracket the is not for this
# /s keeps a

# Apply the function to the tweet_text column
text["tweet_text"] = text["tweet_text"].apply(remove_special_characters)

# Display first 5 rows
print(text["tweet_text"].head())

0    data cleaning   is      very    important
1           caf mnchen is beautful but costly
2                breaking news ai nlp research
3            u r the best btw ill c u 2morrow
4          123456789 numbers should be removed
Name: tweet_text, dtype: object

7. Remove Email

In [ ]:
import re

# Function to remove email addresses
def remove_email(text):
    return re.sub(r'\S+@\S+', '', str(text))
# \S matches any non space character . it matches anything expect space
# + means one or more
# @ matches the symbol

# Apply the function to the column
text["tweet_text"] = text["tweet_text"].apply(remove_email)

# Display first 5 rows
print(text["tweet_text"].head())

0    data cleaning   is      very    important
1           caf mnchen is beautful but costly
2                breaking news ai nlp research
3            u r the best btw ill c u 2morrow
4          123456789 numbers should be removed
Name: tweet_text, dtype: object

8. Remove Phone Number

In [ ]:
import re

# Function to remove 10-digit phone numbers
def remove_phone_number(text):
    return re.sub(r'\b\d{10}\b', '', str(text))

# \b is boundary
# |941234567| \b is starting and \b in ending
# /d is for digits
# {10} match exactly 10 digits


# Apply the function to the tweet_text column
text["tweet_text"] = text["tweet_text"].apply(remove_phone_number)

# Display first 5 rows
print(text["tweet_text"].head())

0    data cleaning   is      very    important
1           caf mnchen is beautful but costly
2                breaking news ai nlp research
3            u r the best btw ill c u 2morrow
4          123456789 numbers should be removed
Name: tweet_text, dtype: object

9. Remove @mentions

In [ ]:
import re

# Function to remove @mentions
def remove_mentions(text):
    return re.sub(r'@\w+', '', str(text))
    # w any word character

# Apply the function to the tweet_text column
text["tweet_text"] = text["tweet_text"].apply(remove_mentions)

# Display first 5 rows
print(text["tweet_text"].head())

0    data cleaning   is      very    important
1           caf mnchen is beautful but costly
2                breaking news ai nlp research
3            u r the best btw ill c u 2morrow
4          123456789 numbers should be removed
Name: tweet_text, dtype: object

11. Remove Emojie

In [ ]:
pip install emoji

Requirement already satisfied: emoji in /usr/local/lib/python3.12/dist-packages (2.15.0)

In [ ]:
import emoji

# Function to remove emojis
def remove_emoji(text):
    return emoji.replace_emoji(str(text), replace='')

# Apply the function to the tweet_text column
text["tweet_text"] = text["tweet_text"].apply(remove_emoji)

# Display first 5 rows
print(text["tweet_text"].head())

0    data cleaning   is      very    important
1           caf mnchen is beautful but costly
2                breaking news ai nlp research
3            u r the best btw ill c u 2morrow
4          123456789 numbers should be removed
Name: tweet_text, dtype: object

12. Expand Chat words

In [ ]:
# Dictionary of chat words
chat_words = {
    "u": "you",
    "r": "are",
    "btw": "by the way",
    "2morrow": "tomorrow"
}

# Function to replace chat words
def replace_chat_words(text):

    # Split the sentence into words
    words = str(text).split()

    new_words = []

    # Replace chat words if present
    for word in words:
        new_words.append(chat_words.get(word, word))

    # Join the words back into a sentence
    return " ".join(new_words)

# Apply the function to the tweet_text column
text["tweet_text"] = text["tweet_text"].apply(replace_chat_words)

# Display first 5 rows
print(text["tweet_text"].head())

0                   data cleaning is very important
1                 caf mnchen is beautful but costly
2                     breaking news ai nlp research
3    you are the best by the way ill c you tomorrow
4               123456789 numbers should be removed
Name: tweet_text, dtype: object

13. Normalize repeated letetr

In [ ]:
import re

# Function to normalize repeated characters
# Example:
# Heeeyyy  -> Hey
# broooo   -> bro
# coooool  -> col
def normalize_repeated_characters(text):
    return re.sub(r'(.)\1{2,}', r'\1', str(text))

# Apply the function to the tweet_text column
text["tweet_text"] = text["tweet_text"].apply(normalize_repeated_characters)

# Display first 5 rows
print(text["tweet_text"].head())

0                   data cleaning is very important
1                 caf mnchen is beautful but costly
2                     breaking news ai nlp research
3    you are the best by the way ill c you tomorrow
4               123456789 numbers should be removed
Name: tweet_text, dtype: object

14. Remove accented character

In [ ]:
# Café - Cafe

In [ ]:
pip install unidecode

Requirement already satisfied: unidecode in /usr/local/lib/python3.12/dist-packages (1.4.0)

In [ ]:
from unidecode import unidecode

# Function to remove accented characters
def remove_accented_characters(text):
    return unidecode(str(text))

# Apply the function to the tweet_text column
text["tweet_text"] = text["tweet_text"].apply(remove_accented_characters)

# Display first 5 rows
print(text["tweet_text"].head())

0                   data cleaning is very important
1                 caf mnchen is beautful but costly
2                     breaking news ai nlp research
3    you are the best by the way ill c you tomorrow
4               123456789 numbers should be removed
Name: tweet_text, dtype: object

15 Remove Special Charcacter

In [ ]:
 import re

# Function to keep only alphabets and spaces
def remove_special_characters(text):
    return re.sub(r'[^a-zA-Z\s]', '', str(text))

# Apply the function to the tweet_text column
text["tweet_text"] = text["tweet_text"].apply(remove_special_characters)

# Display first 5 rows
print(text["tweet_text"].head())

0                   data cleaning is very important
1                 caf mnchen is beautful but costly
2                     breaking news ai nlp research
3    you are the best by the way ill c you tomorrow
4                         numbers should be removed
Name: tweet_text, dtype: object

16. Remove Extra Space

In [ ]:
# Function to remove extra spaces
def remove_extra_spaces(text):
    return " ".join(str(text).split())

# Apply the function to the tweet_text column
text["tweet_text"] = text["tweet_text"].apply(remove_extra_spaces)

# Display first 5 rows
print(text["tweet_text"].head())

0                   data cleaning is very important
1                 caf mnchen is beautful but costly
2                     breaking news ai nlp research
3    you are the best by the way ill c you tomorrow
4                         numbers should be removed
Name: tweet_text, dtype: object

17. Tokenization

In [ ]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
from nltk.tokenize import word_tokenize

# Function to tokenize each tweet
def tokenize_text(text):
    return word_tokenize(str(text))

# Apply tokenization to the tweet_text column
text["tweet_text"] = text["tweet_text"].apply(tokenize_text)

# Display first 5 rows
print(text["tweet_text"].head())

0                [data, cleaning, is, very, important]
1             [caf, mnchen, is, beautful, but, costly]
2                  [breaking, news, ai, nlp, research]
3    [you, are, the, best, by, the, way, ill, c, yo...
4                       [numbers, should, be, removed]
Name: tweet_text, dtype: object

18. Stop word remoeable

In [ ]:
import nltk

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords

# Load English stopwords
stop_words = set(stopwords.words("english"))

# Keep important words
important_words = {"not", "no", "never"}

stop_words = stop_words - important_words

# Function to remove stopwords
def remove_stopwords(words):
    filtered = []

    for word in words:
        if word.lower() not in stop_words:
            filtered.append(word)

    return filtered

# Apply to the tokenized tweet_text column
text["tweet_text"] = text["tweet_text"].apply(remove_stopwords)

# Display first 5 rows
print(text["tweet_text"].head())

0            [data, cleaning, important]
1        [caf, mnchen, beautful, costly]
2    [breaking, news, ai, nlp, research]
3          [best, way, ill, c, tomorrow]
4                     [numbers, removed]
Name: tweet_text, dtype: object

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

19. Stemming

In [ ]:
from nltk.stem import PorterStemmer

# Create Porter Stemmer object
stemmer = PorterStemmer()

# Function to stem words
def stemming(words):
    stemmed = []

    for word in words:
        stemmed.append(stemmer.stem(word))

    return stemmed

# Apply stemming to the tweet_text column
text["tweet_text"] = text["tweet_text"].apply(stemming)

# Display first 5 rows
print(text["tweet_text"].head())

0               [data, clean, import]
1        [caf, mnchen, beaut, costli]
2    [break, news, ai, nlp, research]
3       [best, way, ill, c, tomorrow]
4                     [number, remov]
Name: tweet_text, dtype: object

20. Lemmitization

In [ ]:
import nltk

# Download WordNet resources (run once)
nltk.download('wordnet')
nltk.download('omw-1.4')

from nltk.stem import WordNetLemmatizer

# Create lemmatizer object
lemmatizer = WordNetLemmatizer()

# Function to lemmatize words
def lemmatize_words(words):
    lemmatized = []

    for word in words:
        lemmatized.append(lemmatizer.lemmatize(word))

    return lemmatized

# Apply lemmatization to the tweet_text column
text["tweet_text"] = text["tweet_text"].apply(lemmatize_words)

# Display first 5 rows
print(text["tweet_text"].head())

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

0               [data, clean, import]
1        [caf, mnchen, beaut, costli]
2    [break, news, ai, nlp, research]
3       [best, way, ill, c, tomorrow]
4                     [number, remov]
Name: tweet_text, dtype: object